# Generated by Django 3.0.5 on 2021-08-26 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='customer_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('password', models.CharField(max_length=30, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=30, null=True)),
                ('Category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecommerce_App.Category')),
            ],
        ),
        migrations.CreateModel(
            name='prodtable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30, null=True)),
                ('Brand', models.CharField(max_length=30, null=True)),
                ('Quantity', models.IntegerField(null=True)),
                ('Price', models.FloatField(null=True)),
                ('Stock', models.IntegerField(null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('edate', models.DateField(null=True)),
                ('status', models.BooleanField(null=True)),
                ('Category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecommerce_App.Category')),
                ('Subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecommerce_App.Subcategory')),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce_App.customer_table')),
            ],
        ),
    ]
