# Generated by Django 3.0.5 on 2021-08-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usertable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=30, null=True)),
                ('Lname', models.CharField(max_length=30, null=True)),
                ('Email', models.CharField(max_length=30, null=True)),
                ('Password', models.CharField(max_length=30, null=True)),
                ('Rpassword', models.CharField(max_length=30, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
    ]
