# Generated by Django 3.0.5 on 2021-08-26 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_App', '0003_auto_20210826_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodtable',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecommerce_App.customer_table'),
        ),
    ]
