# Generated by Django 3.0.5 on 2021-08-26 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_App', '0004_auto_20210826_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_table',
            old_name='name',
            new_name='cusname',
        ),
        migrations.RenameField(
            model_name='prodtable',
            old_name='name',
            new_name='cusname',
        ),
    ]
